In [1]:
import tensorflow as tf
#Deklarujemy, że chcemy używać biblioteki TensorFlow i będziemy się do niej odwoływać pod skróconą nazwą "tf".
#Here we call TensorFlow library in for later usage.

In [2]:
#ZMIENNA (inicjowanie)
#Creates variable:
zero = tf.Variable(0)
#Co się tłumaczy: nazwa_zmiennej = tf.Variable(wartość_zmiennej). Pamiętaj o wielkim "V".

In [3]:
#STAŁA (inicjowanie)
#Creates constant:
one = tf.constant(1)
#Konstrukcja j.w. Stała, jak sama nazwa wskazuje, się nie zmienia, tak więc uważaj gdzie ich używasz...

In [4]:
#SUMUJ (metoda)
#adds variables, constants
new_value = tf.add(zero,one)
#W tym przykładzie zsumowaliśmy wartości zmiennej 'zero' i stałej 'jeden'.

In [5]:
#ZMIEŃ WARTOŚĆ (metoda)
#assigns new wvlue to an existing variable.
update = tf.assign(zero,new_value)
#Dosłownie: nazwa_zmiennej = tf.assign(nazwa_zmiennej_której_wartość_zmieniamy,nowa_wartość). Tu zmienia wartość 'zera' na sumę "zera" i "one", czyli na 1.

In [6]:
#Pamiętaj, że Stałe nie podlegają zmianom. Kod, np.:
#"update_constant = tf.assign(one,new_value)" wywali błąd.

In [7]:
#Zainicjalizuj_WSZYSTKIE_zmienne
init_op = tf.global_variables_initializer()
#Zawsze pamiętaj, żeby "zainicjalizować wszystkie zmienne".

In [25]:
#Definiujemy sesję TF.
sess = tf.Session()
#Inicjalizujemy zmienne w sesji.
sess.run(init_op)
#Raz zainicjalizowana sesja jest ciągle AKTYWNA 
#do zamknięcia odpowiednią metodą 'session.close()'.

In [24]:
#Drukuj stan elementu sesji (?)
print(sess.run(zero))

0


In [9]:
#FOR - PĘTLA
#Przykład jak pisać pętle FOR.
for _ in range(5):
        sess.run(update)
        print(sess.run(zero))
#Ta pętla zapętli się 5 razy za każdym razem wypluwając update wartości funkcji.

1
2
3
4
5


In [12]:
#Operacje na ciągach znaków.
hello = tf.constant('hello')
world = tf.constant('world')
helloworld = tf.add(hello,world)
print(sess.run(helloworld))
#Tutaj mamy oczywisty przykład łączenia dwóch stałych ciągów w jeden.

b'helloworld'


In [20]:
#PODSTAWNIK
#Placeholder
a = tf.placeholder(tf.float32)
#c = tf.placeholder(tf.rodzaj_podstawnika). W przykładzie jest najpopularniejszy Float32.
#Tworzy nowy podstawnik o nazwie "a" typu liczby dziesięte.


In [21]:
b=a*2

In [22]:
#Wstawianie do podstawnika wartości skalarnej. (Wektora/Tensora)
#Feeding scalar to placeholder
#result=sess.run(b,feed_dict={a:3}) <- lub feed_dict="nazwa_zmiennej_słownika"
result=sess.run(b,{a:3})
#Podobno obydwie powyższe metody działają tak samo.
#feed_dict sprawia po prostu, że kod jest bardziej przejrzysty.
print(result)
#W tym przykładzie odpalamy w działającej już sesji podstawnik z wartością 'b' dla 'a'=3

6.0


In [26]:
#Do podstawnika można też wrzucać wektory.
result=sess.run(b,feed_dict={a:[3,4,5]})
print(result)

[ 6.  8. 10.]


In [28]:
#W tym wektory wielowymiarowe.
dictionary={a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}
#Raczej nie będziemy w ten sposób ręcznie przygotowywać zmiennej, ale założenie właśnie tak wygląda.
#Dane będziemy wczytywać do słownika np. z pliku CSV a potem podstawiać jak w przykładzie.
result=sess.run(b,feed_dict=dictionary)
#Na przykładzie wektor 3x4x2
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [29]:
#ZAMYKANIE SESJI
sess.close()
#Jeśli tego nie zrobisz, to komputer się może zacinać,
#bo nie odblokujesz sobie zasobów.

In [31]:
#Popularna alternatywna konstrukcja inicjowania sesji - w bloku.
with tf.Session() as sess:
    result = sess.run(hello+world)
    print(result)
    #Więcej linijek kodu
    #ale wszystkie zostaną wykonane w ramach tej sesji
    #Tej konstrukcji nie trzeba zamykać sess.close()
    #Zamyka się sama po wykonaniu ostatniego wyrażenia w bloku.

b'helloworld'
